### ISSUE TITLE
Support Terraform variables

### ISSUE THREAD

**Issue by Fodoj** [padok-team/tfautomv#22]
As of now, `tfautomv` does not allow to path Terraform variables and variable files. Are there plans to introduce this feature?

**Comment by busser** [comment]
Hi @Fodoj, thanks for opening this issue!

If I understand you correctly, we are talking about using the `-var` and `-var-file` flags for the `terraform plan` command that `tfautomv` runs. This is already possible by using the [`TF_CLI_ARGS_plan` environment variable](https://www.terraform.io/cli/config/environment-variables#tf_cli_args-and-tf_cli_args_name), which is a native Terraform feature. For example:

```bash
TF_CLI_ARGS_plan="-var-file=production.tfvars" tfautomv
```

You are likely not the only one who needs to do this, so I think we should explicitly document it. We are currently revamping our documentation for the v0.4 release, so I will add this to our backlog.

Is using this environment variable enough for your use case?

**Comment by busser** [comment]
PR #21 will document this configuration option.

**Comment by Fodoj** [comment]
I've actually tried it this way, but it did not work for me :) I will try again, perhaps something went wrong due to my local aliases. Thanks!
